### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by Tanguille** [Martlark/pg_dump#18]
Running following configuration in my compose file:
```yaml
 postgres-backup:
    image: martlark/pg_dump:16.1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
     - ./.env.docker
    environment:
      - CRON_SCHEDULE=0 * * * * # Every hour
      - RETAIN_COUNT=24 # Full day
     volumes:
      - ${HOME}/backups:/dump
  ```

This is the output I get:
```sh
Starting pg_dump
tee: /dump/dump-log: Permission denied
WARN: No password file found!
It is suggested that a docker secrets file is used for security concerns.
/entrypoint.sh: line 75: /dump/dump-log: Permission denied
tail: cannot open '/dump/dump-log' for reading: No such file or directory
```

Any idea on how I can fix this? Read all the documentation I could find but did find nothing about permissions
